### PR TITLE
added exporter errors

### PR DESCRIPTION
**Pull request by Shubham-Chavan-Bentley**
Added exporter-errors

### CODE REVIEW

**Review by jffmarker — COMMENTED** [review]
Why do you want to keep all of the existing data in this copy? I would think you want to create something specific to exporters. The existing categories, KBs, and error list don't seem very related to exporters.

**Comment by Shubham-Chavan-Bentley** [comment]
I thought we are going to add exporter errors in the same list as connector errors, so all the errors could be in one place, but if we want to keep them separate then, should I create a .json file just specific to exporters?

**Comment by jffmarker** [comment]
> I thought we are going to add exporter errors in the same list as connector errors, so all the errors could be in one place, but if we want to keep them separate then, should I create a .json file just specific to exporters?

I don't see a reason that we need to tie the two together. If you like the schema of the existing data you are free to borrow it, but it's not obvious to me that Connectors and Exporters will need to share error information, so making it distinct will give you freedom to customize to your workflows, right? Do you foresee an advantage to always keeping them locked together?

**Comment by Shubham-Chavan-Bentley** [comment]
Yeah, you're right! I think keeping them separate will make more sense and will give more freedom for customization in the future. I will work on it again, and I'll separate exporter errors from connector errors. Thanks!

**Comment by Shubham-Chavan-Bentley** [comment]
I have updated the exporter errors, and I tried to keep connector errors and exporter errors separate, Thanks for letting me use the existing schema, You can review the PR now. Thanks!

**Review by jffmarker — APPROVED** [review]

**Pull request merged**
