### PR TITLE
Update fatal-errors.json

### PR DESCRIPTION
**Pull request by tejal2610**
Added new errors to return specific message to user. 
This changes are related to FUKUI bug. 
[Bug 1182173](https://dev.azure.com/bentleycs/beconnect/_workitems/edit/1182173): Unclear error message when URL expires before it gets downloaded on the node

### CODE REVIEW

**Comment by James-QSE** [comment]
Although it is necessary to keep adding the new errors to the tail of the "errors" section, the "KbArticleLinks" can be in any order. It would be better to keep them in alphabetical order (matching the existing ones).

**Comment by James-QSE** [comment]
Is "other" the correct category for these errors? There is already a category "file_access", which would seem appropriate here.

**Comment by tejal2610** [comment]
> Is "other" the correct category for these errors? There is already a category "file_access", which would seem appropriate here.

Agree with you, I will change the category.

**Comment by tejal2610** [comment]
> Although it is necessary to keep adding the new errors to the tail of the "errors" section, the "KbArticleLinks" can be in any order. It would be better to keep them in alphabetical order (matching the existing ones).

I did not notice this before. Re-arranged links and persisted the pattern.

**Review by jffmarker — APPROVED** [review]

**Pull request merged**
