### PR TITLE
Updated the Excessive element count message

### PR DESCRIPTION
**Pull request by sushmitasathe**
Updated the Element count limit to 1.5 million so updated message.

### CODE REVIEW

**Review by James-QSE — COMMENTED** [review]
With connectors, it is recommended that there should be a KbLinkId for a knowledge base item for user fixable errors. I don't know what the policy is for exporters, but I would say that the same policy be followed.

**Comment by sushmitasathe** [comment]
Updating the branch with latest changes

**Review by James-QSE — APPROVED** [review]
The message gives sufficient information for a user to work with. A KbLinkId may follow when a Knowledge Base article is written for Exporters.

**Comment by jffmarker** [comment]
Keep in mind many other messages are format strings... so if this number is likely to change again, you could leave a format placeholder for the number instead so that next time you don't need to independently update the translatable error string.

**Pull request merged**
