### PR TITLE
Added standard error for Imodel Permission

### PR DESCRIPTION
**Pull request by Shubham-Chavan-Bentley**

### CODE REVIEW

**Comment by James-QSE** [comment]
@Shubham-Chavan-Bentley is this message going to be reported when we know that the user does not have permission (in which case it would be user fixable, and should probably have a KbArticleLink explaining where the permissions may be set), or will it be reported when we are unable to communicate with the iModelHub at all (which is probably not user fixable)

**Comment by Shubham-Chavan-Bentley** [comment]
No. It's the client that we use that won't have permission to the iModel. So, the user cannot really fix it, It can happen when there's an issue with the self-invite workflow.

**Comment by James-QSE** [comment]
The error does not really fit the style of most of the others. It should probably be called ErrorCheckingImodelPermission, and the word "Occurred" should not be capitalized in the message.

**Comment by Shubham-Chavan-Bentley** [comment]
Sorry, I'll just fix it up

**Comment by Shubham-Chavan-Bentley** [comment]
@James-QSE  Thanks for noticing the difference in styles!

**Review by James-QSE — APPROVED** [review]
That fits the pattern better.

**Pull request merged**
